const albumsData = [
  {
    title: "Taylor Swift",
    releaseDate: "2006-10-24",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/1/1f/Taylor_Swift_-_Taylor_Swift.png",
    description: "The self-titled debut that started it all. A country-pop masterpiece exploring young love and heartbreak.",
    songs: [
      { title: "Tim McGraw", duration: "3:52" },
      { title: "Picture to Burn", duration: "2:53" },
      { title: "Teardrops on My Guitar", duration: "3:33" },
      { title: "A Place in this World", duration: "3:19" },
      { title: "Cold As You", duration: "3:59" },
      { title: "The Outside", duration: "3:27" },
      { title: "Tied Together with a Smile", duration: "4:08" },
      { title: "Stay Beautiful", duration: "3:56" },
      { title: "Should've Said No", duration: "4:02" },
      { title: "Mary's Song (Oh My My My)", duration: "3:33" },
      { title: "Our Song", duration: "3:21" },
      { title: "I'm Only Me When I'm With You", duration: "3:33" },
      { title: "Invisible", duration: "3:23" },
      { title: "A Perfectly Good Heart", duration: "3:40" }
    ]
  },
  {
    title: "Fearless (Taylor's Version)",
    releaseDate: "2021-04-09",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/5/5b/Fearless_%28Taylor%27s_Version%29_%282021_album_cover%29_by_Taylor_Swift.png",
    description: "The first re-recorded album. A celebration of youth, magic, and the courage to be fearless.",
    songs: [
      { title: "Fearless (Taylor's Version)", duration: "4:01" },
      { title: "Fifteen (Taylor's Version)", duration: "4:54" },
      { title: "Love Story (Taylor's Version)", duration: "3:55" },
      { title: "Hey Stephen (Taylor's Version)", duration: "4:14" },
      { title: "White Horse (Taylor's Version)", duration: "3:54" },
      { title: "You Belong with Me (Taylor's Version)", duration: "3:51" },
      { title: "Breathe (feat. Colbie Caillat) (Taylor's Version)", duration: "4:23" },
      { title: "Tell Me Why (Taylor's Version)", duration: "3:38" },
      { title: "You're Not Sorry (Taylor's Version)", duration: "4:21" },
      { title: "The Way I Loved You (Taylor's Version)", duration: "4:03" },
      { title: "Forever & Always (Taylor's Version)", duration: "3:45" },
      { title: "The Best Day (Taylor's Version)", duration: "4:05" },
      { title: "Change (Taylor's Version)", duration: "4:39" },
      { title: "Today Was a Fairytale (Taylor's Version)", duration: "4:01" },
      { title: "You All Over Me (feat. Maren Morris) (From The Vault)", duration: "3:40" },
      { title: "Mr. Perfectly Fine (From The Vault)", duration: "4:37" },
      { title: "We Were Happy (From The Vault)", duration: "4:04" },
      { title: "That's When (feat. Keith Urban) (From The Vault)", duration: "3:09" },
      { title: "Don't You (From The Vault)", duration: "3:28" },
      { title: "Bye Bye Baby (From The Vault)", duration: "4:02" }
    ]
  },
  {
    title: "Speak Now (Taylor's Version)",
    releaseDate: "2023-07-07",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/5/5a/Taylor_Swift_-_Speak_Now_%28Taylor%27s_Version%29.png",
    description: "An entirely self-written album. Confessions, open letters, and the electric spark of being young.",
    songs: [
      { title: "Mine (Taylor's Version)", duration: "3:51" },
      { title: "Sparks Fly (Taylor's Version)", duration: "4:21" },
      { title: "Back to December (Taylor's Version)", duration: "4:54" },
      { title: "Speak Now (Taylor's Version)", duration: "4:02" },
      { title: "Dear John (Taylor's Version)", duration: "6:43" },
      { title: "Mean (Taylor's Version)", duration: "3:58" },
      { title: "The Story of Us (Taylor's Version)", duration: "4:27" },
      { title: "Never Grow Up (Taylor's Version)", duration: "4:52" },
      { title: "Enchanted (Taylor's Version)", duration: "5:53" },
      { title: "Better Than Revenge (Taylor's Version)", duration: "3:40" },
      { title: "Innocent (Taylor's Version)", duration: "5:01" },
      { title: "Haunted (Taylor's Version)", duration: "4:05" },
      { title: "Last Kiss (Taylor's Version)", duration: "6:09" },
      { title: "Long Live (Taylor's Version)", duration: "5:17" },
      { title: "Ours (Taylor's Version)", duration: "3:55" },
      { title: "Superman (Taylor's Version)", duration: "4:34" },
      { title: "Electric Touch (feat. Fall Out Boy) (From The Vault)", duration: "4:26" },
      { title: "When Emma Falls in Love (From The Vault)", duration: "4:12" },
      { title: "I Can See You (From The Vault)", duration: "4:33" },
      { title: "Castles Crumbling (feat. Hayley Williams) (From The Vault)", duration: "5:06" },
      { title: "Foolish One (From The Vault)", duration: "5:11" },
      { title: "Timeless (From The Vault)", duration: "5:21" }
    ]
  },
  {
    title: "Red (Taylor's Version)",
    releaseDate: "2021-11-12",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/4/47/Taylor_Swift_-_Red_%28Taylor%27s_Version%29.png",
    description: "The experimental pop-rock transition. A mosaic of feelings that are all 'Red'.",
    songs: [
      { title: "State of Grace (Taylor's Version)", duration: "4:55" },
      { title: "Red (Taylor's Version)", duration: "3:43" },
      { title: "Treacherous (Taylor's Version)", duration: "4:02" },
      { title: "I Knew You Were Trouble (Taylor's Version)", duration: "3:39" },
      { title: "All Too Well (Taylor's Version)", duration: "5:29" },
      { title: "22 (Taylor's Version)", duration: "3:50" },
      { title: "I Almost Do (Taylor's Version)", duration: "4:04" },
      { title: "We Are Never Ever Getting Back Together (Taylor's Version)", duration: "3:13" },
      { title: "Stay Stay Stay (Taylor's Version)", duration: "3:25" },
      { title: "The Last Time (feat. Gary Lightbody) (Taylor's Version)", duration: "4:59" },
      { title: "Holy Ground (Taylor's Version)", duration: "3:22" },
      { title: "Sad Beautiful Tragic (Taylor's Version)", duration: "4:44" },
      { title: "The Lucky One (Taylor's Version)", duration: "4:00" },
      { title: "Everything Has Changed (feat. Ed Sheeran) (Taylor's Version)", duration: "4:05" },
      { title: "Starlight (Taylor's Version)", duration: "3:40" },
      { title: "Begin Again (Taylor's Version)", duration: "3:58" },
      { title: "Better Man (From The Vault)", duration: "4:57" },
      { title: "Nothing New (feat. Phoebe Bridgers) (From The Vault)", duration: "4:18" },
      { title: "Babe (From The Vault)", duration: "3:44" },
      { title: "Message In A Bottle (From The Vault)", duration: "3:45" },
      { title: "I Bet You Think About Me (feat. Chris Stapleton) (From The Vault)", duration: "4:45" },
      { title: "Forever Winter (From The Vault)", duration: "4:23" },
      { title: "Run (feat. Ed Sheeran) (From The Vault)", duration: "4:00" },
      { title: "The Very First Night (From The Vault)", duration: "3:20" },
      { title: "All Too Well (10 Minute Version) (Taylor's Version) (From The Vault)", duration: "10:13" }
    ]
  },
  {
    title: "1989 (Taylor's Version)",
    releaseDate: "2023-10-27",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/d/d5/Taylor_Swift_-_1989_%28Taylor%27s_Version%29.png",
    description: "The pop bible re-recorded. Neon lights, New York City, and the perfect synth-pop sound.",
    songs: [
      { title: "Welcome to New York (Taylor's Version)", duration: "3:32" },
      { title: "Blank Space (Taylor's Version)", duration: "3:51" },
      { title: "Style (Taylor's Version)", duration: "3:51" },
      { title: "Out of the Woods (Taylor's Version)", duration: "3:55" },
      { title: "All You Had to Do Was Stay (Taylor's Version)", duration: "3:13" },
      { title: "Shake It Off (Taylor's Version)", duration: "3:39" },
      { title: "I Wish You Would (Taylor's Version)", duration: "3:27" },
      { title: "Bad Blood (Taylor's Version)", duration: "3:31" },
      { title: "Wildest Dreams (Taylor's Version)", duration: "3:40" },
      { title: "How You Get the Girl (Taylor's Version)", duration: "4:07" },
      { title: "This Love (Taylor's Version)", duration: "4:10" },
      { title: "I Know Places (Taylor's Version)", duration: "3:15" },
      { title: "Clean (Taylor's Version)", duration: "4:31" },
      { title: "Wonderland (Taylor's Version)", duration: "4:05" },
      { title: "You Are In Love (Taylor's Version)", duration: "4:27" },
      { title: "New Romantics (Taylor's Version)", duration: "3:50" },
      { title: "Slut! (From The Vault)", duration: "3:00" },
      { title: "Say Don't Go (From The Vault)", duration: "4:39" },
      { title: "Now That We Don't Talk (From The Vault)", duration: "2:26" },
      { title: "Suburban Legends (From The Vault)", duration: "2:51" },
      { title: "Is It Over Now? (From The Vault)", duration: "3:49" }
    ]
  },
  {
    title: "reputation",
    releaseDate: "2017-11-10",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/f/f2/Taylor_Swift_-_Reputation.png",
    description: "There will be no explanation. There will just be reputation.",
    songs: [
      { title: "...Ready for It?", duration: "3:28" },
      { title: "End Game (feat. Ed Sheeran and Future)", duration: "4:04" },
      { title: "I Did Something Bad", duration: "3:58" },
      { title: "Don't Blame Me", duration: "3:56" },
      { title: "Delicate", duration: "3:52" },
      { title: "Look What You Made Me Do", duration: "3:31" },
      { title: "So It Goes...", duration: "3:47" },
      { title: "Gorgeous", duration: "3:29" },
      { title: "Getaway Car", duration: "3:53" },
      { title: "King of My Heart", duration: "3:34" },
      { title: "Dancing with Our Hands Tied", duration: "3:31" },
      { title: "Dress", duration: "3:50" },
      { title: "This Is Why We Can't Have Nice Things", duration: "3:27" },
      { title: "Call It What You Want", duration: "3:23" },
      { title: "New Year's Day", duration: "3:55" }
    ]
  },
  {
    title: "Lover",
    releaseDate: "2019-08-23",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png",
    description: "A love letter to love, in all its madness and glory.",
    songs: [
      { title: "I Forgot That You Existed", duration: "2:51" },
      { title: "Cruel Summer", duration: "2:58" },
      { title: "Lover", duration: "3:41" },
      { title: "The Man", duration: "3:10" },
      { title: "The Archer", duration: "3:31" },
      { title: "I Think He Knows", duration: "2:53" },
      { title: "Miss Americana & The Heartbreak Prince", duration: "3:54" },
      { title: "Paper Rings", duration: "3:42" },
      { title: "Cornelia Street", duration: "4:47" },
      { title: "Death by a Thousand Cuts", duration: "3:19" },
      { title: "London Boy", duration: "3:10" },
      { title: "Soon You'll Get Better (feat. The Chicks)", duration: "3:21" },
      { title: "False God", duration: "3:20" },
      { title: "You Need to Calm Down", duration: "2:51" },
      { title: "Afterglow", duration: "3:43" },
      { title: "ME! (feat. Brendon Urie)", duration: "3:13" },
      { title: "It's Nice to Have a Friend", duration: "2:30" },
      { title: "Daylight", duration: "4:53" }
    ]
  },
  {
    title: "folklore",
    releaseDate: "2020-07-24",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/f/f8/Taylor_Swift_-_Folklore.png",
    description: "In isolation my imagination has run wild and this album is the result.",
    songs: [
      { title: "the 1", duration: "3:30" },
      { title: "cardigan", duration: "3:59" },
      { title: "the last great american dynasty", duration: "3:51" },
      { title: "exile (feat. Bon Iver)", duration: "4:45" },
      { title: "my tears ricochet", duration: "4:15" },
      { title: "mirrorball", duration: "3:29" },
      { title: "seven", duration: "3:28" },
      { title: "august", duration: "4:21" },
      { title: "this is me trying", duration: "3:15" },
      { title: "illicit affairs", duration: "3:10" },
      { title: "invisible string", duration: "4:12" },
      { title: "mad woman", duration: "3:57" },
      { title: "epiphany", duration: "4:49" },
      { title: "betty", duration: "4:54" },
      { title: "peace", duration: "3:54" },
      { title: "hoax", duration: "3:40" },
      { title: "the lakes", duration: "3:31" }
    ]
  },
  {
    title: "evermore",
    releaseDate: "2020-12-11",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/0/0a/Taylor_Swift_-_Evermore.png",
    description: "We just couldn't stop writing songs. folklore's sister album.",
    songs: [
      { title: "willow", duration: "3:34" },
      { title: "champagne problems", duration: "4:04" },
      { title: "gold rush", duration: "3:05" },
      { title: "tis the damn season", duration: "3:49" },
      { title: "tolerate it", duration: "4:05" },
      { title: "no body, no crime (feat. HAIM)", duration: "3:35" },
      { title: "happiness", duration: "5:15" },
      { title: "dorothea", duration: "3:45" },
      { title: "coney island (feat. The National)", duration: "4:35" },
      { title: "ivy", duration: "4:20" },
      { title: "cowboy like me", duration: "4:35" },
      { title: "long story short", duration: "3:35" },
      { title: "marjorie", duration: "4:17" },
      { title: "closure", duration: "3:00" },
      { title: "evermore (feat. Bon Iver)", duration: "5:04" },
      { title: "right where you left me", duration: "4:05" },
      { title: "it's time to go", duration: "4:14" }
    ]
  },
  {
    title: "Midnights",
    releaseDate: "2022-10-21",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/9/9f/Taylor_Swift_-_Midnights_%28album_cover%29.png",
    description: "13 sleepless nights scattered throughout my life.",
    songs: [
      { title: "Lavender Haze", duration: "3:22" },
      { title: "Maroon", duration: "3:38" },
      { title: "Anti-Hero", duration: "3:20" },
      { title: "Snow On The Beach (feat. Lana Del Rey)", duration: "4:16" },
      { title: "You're On Your Own, Kid", duration: "3:14" },
      { title: "Midnight Rain", duration: "2:54" },
      { title: "Question...?", duration: "3:30" },
      { title: "Vigilante Shit", duration: "2:44" },
      { title: "Bejeweled", duration: "3:14" },
      { title: "Labyrinth", duration: "4:07" },
      { title: "Karma", duration: "3:24" },
      { title: "Sweet Nothing", duration: "3:08" },
      { title: "Mastermind", duration: "3:11" },
      { title: "The Great War", duration: "4:00" },
      { title: "Bigger Than The Whole Sky", duration: "3:38" },
      { title: "Paris", duration: "3:16" },
      { title: "High Infidelity", duration: "3:53" },
      { title: "Glitch", duration: "2:28" },
      { title: "Would've, Could've, Should've", duration: "4:20" },
      { title: "Dear Reader", duration: "3:45" }
    ]
  },
  {
    title: "The Tortured Poets Department",
    releaseDate: "2024-04-19",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/6/6e/Taylor_Swift_%E2%80%93_The_Tortured_Poets_Department_%28album_cover%29.png",
    description: "All's fair in love and poetry.",
    songs: [
      { title: "Fortnight (feat. Post Malone)", duration: "3:48" },
      { title: "The Tortured Poets Department", duration: "4:53" },
      { title: "My Boy Only Breaks His Favorite Toys", duration: "2:51" },
      { title: "Down Bad", duration: "4:21" },
      { title: "So Long, London", duration: "4:22" },
      { title: "But Daddy I Love Him", duration: "5:40" },
      { title: "Fresh Out The Slammer", duration: "3:30" },
      { title: "Florida!!! (feat. Florence + The Machine)", duration: "3:35" },
      { title: "Guilty as Sin?", duration: "4:14" },
      { title: "Who's Afraid of Little Old Me?", duration: "5:34" },
      { title: "I Can Fix Him (No Really I Can)", duration: "2:36" },
      { title: "loml", duration: "4:37" },
      { title: "I Can Do It With a Broken Heart", duration: "3:38" },
      { title: "The Smallest Man Who Ever Lived", duration: "4:05" },
      { title: "The Alchemy", duration: "3:17" },
      { title: "Clara Bow", duration: "3:36" },
      { title: "The Black Dog", duration: "3:48" },
      { title: "The Manuscript", duration: "3:44" }
    ]
  },
  {
    title: "Life of a Showgirl",
    releaseDate: "2025-05-13",
    coverImage: "/showgirl.png",
    description: "The dazzling spectacle of a life on stage. Authentic, glittering, and raw.",
    songs: [
      { title: "Standing Ovation", duration: "3:45" },
      { title: "Backstage Pass", duration: "4:10" },
      { title: "Glitter in my Hair", duration: "3:25" },
      { title: "The Dressing Room", duration: "4:15" },
      { title: "Under the Spotlight", duration: "3:50" },
      { title: "Intermission", duration: "2:30" },
      { title: "Act II", duration: "4:00" },
      { title: "Encore", duration: "4:20" },
      { title: "Final Bow", duration: "5:15" },
      { title: "The Afterparty", duration: "3:35" },
      { title: "Silence is Gold", duration: "4:40" },
      { title: "Life of a Showgirl", duration: "4:05" }
    ]
  }
];

module.exports = albumsData;
